apiVersion: v1
kind: Pod
metadata:
  name: rabbit-mq
spec:
  hostNetwork: true 
  containers:
  - name: rabbit-mq
    image: ursspraveenreddy/test08:latest
    ports:
    - containerPort: 15671
      protocol: TCP
