apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: service	
spec:
  hostNetwork: true
  containers:
  - name: tomcat
    image:  tomcat
    ports:
    - name:  tomcatport
      containerPort:  8080
      protocol: TCP
