apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name:  nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      project: nginx-project
  template:
    metadata: 
      labels: 
        project: nginx-project
    spec:
      hostNetwork: true
      containers:
      - image: nginx
        name: nginx-rs
        ports:
        - containerPort: 80